/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSupervisionRouteImport } from './routes/_authenticated/supervision'
import { Route as AuthenticatedSolversRouteImport } from './routes/_authenticated/solvers'
import { Route as AuthenticatedSolverGeneratorRouteImport } from './routes/_authenticated/solver-generator'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedInstancesRouteImport } from './routes/_authenticated/instances'
import { Route as AuthenticatedDonneesRouteImport } from './routes/_authenticated/donnees'
import { Route as AuthenticatedCommandesRouteImport } from './routes/_authenticated/commandes'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupervisionRoute =
  AuthenticatedSupervisionRouteImport.update({
    id: '/supervision',
    path: '/supervision',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolversRoute = AuthenticatedSolversRouteImport.update({
  id: '/solvers',
  path: '/solvers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolverGeneratorRoute =
  AuthenticatedSolverGeneratorRouteImport.update({
    id: '/solver-generator',
    path: '/solver-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstancesRoute = AuthenticatedInstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonneesRoute = AuthenticatedDonneesRouteImport.update({
  id: '/donnees',
  path: '/donnees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandesRoute = AuthenticatedCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/use-cases': typeof UseCasesRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/app': typeof AuthenticatedAppRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/commandes': typeof AuthenticatedCommandesRoute
  '/donnees': typeof AuthenticatedDonneesRoute
  '/instances': typeof AuthenticatedInstancesRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/solver-generator': typeof AuthenticatedSolverGeneratorRoute
  '/solvers': typeof AuthenticatedSolversRoute
  '/supervision': typeof AuthenticatedSupervisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/use-cases': typeof UseCasesRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/app': typeof AuthenticatedAppRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/commandes': typeof AuthenticatedCommandesRoute
  '/donnees': typeof AuthenticatedDonneesRoute
  '/instances': typeof AuthenticatedInstancesRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/solver-generator': typeof AuthenticatedSolverGeneratorRoute
  '/solvers': typeof AuthenticatedSolversRoute
  '/supervision': typeof AuthenticatedSupervisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/use-cases': typeof UseCasesRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/commandes': typeof AuthenticatedCommandesRoute
  '/_authenticated/donnees': typeof AuthenticatedDonneesRoute
  '/_authenticated/instances': typeof AuthenticatedInstancesRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/solver-generator': typeof AuthenticatedSolverGeneratorRoute
  '/_authenticated/solvers': typeof AuthenticatedSolversRoute
  '/_authenticated/supervision': typeof AuthenticatedSupervisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/features'
    | '/platform'
    | '/pricing'
    | '/use-cases'
    | '/api-keys'
    | '/app'
    | '/clients'
    | '/commandes'
    | '/donnees'
    | '/instances'
    | '/schedules'
    | '/settings'
    | '/solver-generator'
    | '/solvers'
    | '/supervision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/features'
    | '/platform'
    | '/pricing'
    | '/use-cases'
    | '/api-keys'
    | '/app'
    | '/clients'
    | '/commandes'
    | '/donnees'
    | '/instances'
    | '/schedules'
    | '/settings'
    | '/solver-generator'
    | '/solvers'
    | '/supervision'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/architecture'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/features'
    | '/platform'
    | '/pricing'
    | '/use-cases'
    | '/_authenticated/api-keys'
    | '/_authenticated/app'
    | '/_authenticated/clients'
    | '/_authenticated/commandes'
    | '/_authenticated/donnees'
    | '/_authenticated/instances'
    | '/_authenticated/schedules'
    | '/_authenticated/settings'
    | '/_authenticated/solver-generator'
    | '/_authenticated/solvers'
    | '/_authenticated/supervision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  UseCasesRoute: typeof UseCasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/supervision': {
      id: '/_authenticated/supervision'
      path: '/supervision'
      fullPath: '/supervision'
      preLoaderRoute: typeof AuthenticatedSupervisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solvers': {
      id: '/_authenticated/solvers'
      path: '/solvers'
      fullPath: '/solvers'
      preLoaderRoute: typeof AuthenticatedSolversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solver-generator': {
      id: '/_authenticated/solver-generator'
      path: '/solver-generator'
      fullPath: '/solver-generator'
      preLoaderRoute: typeof AuthenticatedSolverGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instances': {
      id: '/_authenticated/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof AuthenticatedInstancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donnees': {
      id: '/_authenticated/donnees'
      path: '/donnees'
      fullPath: '/donnees'
      preLoaderRoute: typeof AuthenticatedDonneesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commandes': {
      id: '/_authenticated/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof AuthenticatedCommandesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCommandesRoute: typeof AuthenticatedCommandesRoute
  AuthenticatedDonneesRoute: typeof AuthenticatedDonneesRoute
  AuthenticatedInstancesRoute: typeof AuthenticatedInstancesRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSolverGeneratorRoute: typeof AuthenticatedSolverGeneratorRoute
  AuthenticatedSolversRoute: typeof AuthenticatedSolversRoute
  AuthenticatedSupervisionRoute: typeof AuthenticatedSupervisionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCommandesRoute: AuthenticatedCommandesRoute,
  AuthenticatedDonneesRoute: AuthenticatedDonneesRoute,
  AuthenticatedInstancesRoute: AuthenticatedInstancesRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSolverGeneratorRoute: AuthenticatedSolverGeneratorRoute,
  AuthenticatedSolversRoute: AuthenticatedSolversRoute,
  AuthenticatedSupervisionRoute: AuthenticatedSupervisionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  UseCasesRoute: UseCasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
